//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MediaMarkup
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "urn:ias:cvss:mm:1.0", ConfigurationName = "MediaMarkupPort")]
    public interface IMediaMarkupPort
    {

        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:mm:1.0/SetMarker")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SetMarkerResponse SetMarker(SetMarkerRequest request);

        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:mm:1.0/GetMarker")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GetMarkerResponse GetMarker(GetMarkerRequest request);

        // CODEGEN: Параметр "Recording" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:mm:1.0/GetMarkedRecordings")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "Recording")]
        GetMarkedRecordingsResponse GetMarkedRecordings(GetMarkedRecordingsRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:mm:1.0/DeleteMarker")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DeleteMarker(string MarkerToken);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:mm:1.0", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        MediaSourceToken,

        /// <remarks/>
        RecordingToken,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:mm:1.0")]
    public partial class MarkerInformation
    {

        private string titleField;

        private System.DateTime fromField;

        private System.DateTime toField;

        private bool toFieldSpecified;

        private MarkerBounds boundsField;

        private System.Xml.XmlElement[] anyField;

        private string tokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.DateTime From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public System.DateTime To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToSpecified
        {
            get
            {
                return this.toFieldSpecified;
            }
            set
            {
                this.toFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public MarkerBounds Bounds
        {
            get
            {
                return this.boundsField;
            }
            set
            {
                this.boundsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 4)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:mm:1.0")]
    public partial class MarkerBounds
    {

        private System.Xml.XmlElement[] anyField;

        private float xField;

        private float yField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/schema")]
    public partial class TrackInformation
    {

        private string trackTokenField;

        private TrackType trackTypeField;

        private string descriptionField;

        private System.DateTime dataFromField;

        private System.DateTime dataToField;

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string TrackToken
        {
            get
            {
                return this.trackTokenField;
            }
            set
            {
                this.trackTokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public TrackType TrackType
        {
            get
            {
                return this.trackTypeField;
            }
            set
            {
                this.trackTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public System.DateTime DataFrom
        {
            get
            {
                return this.dataFromField;
            }
            set
            {
                this.dataFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public System.DateTime DataTo
        {
            get
            {
                return this.dataToField;
            }
            set
            {
                this.dataToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 5)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/schema")]
    public enum TrackType
    {

        /// <remarks/>
        Video,

        /// <remarks/>
        Audio,

        /// <remarks/>
        Metadata,

        /// <remarks/>
        Extended,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/schema")]
    public partial class RecordingSourceInformation
    {

        private string sourceIdField;

        private string nameField;

        private string locationField;

        private string descriptionField;

        private string addressField;

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 0)]
        public string SourceId
        {
            get
            {
                return this.sourceIdField;
            }
            set
            {
                this.sourceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 4)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 5)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/schema")]
    public partial class RecordingInformation
    {

        private string recordingTokenField;

        private RecordingSourceInformation sourceField;

        private System.DateTime earliestRecordingField;

        private bool earliestRecordingFieldSpecified;

        private System.DateTime latestRecordingField;

        private bool latestRecordingFieldSpecified;

        private string contentField;

        private TrackInformation[] trackField;

        private RecordingStatus recordingStatusField;

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string RecordingToken
        {
            get
            {
                return this.recordingTokenField;
            }
            set
            {
                this.recordingTokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public RecordingSourceInformation Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public System.DateTime EarliestRecording
        {
            get
            {
                return this.earliestRecordingField;
            }
            set
            {
                this.earliestRecordingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EarliestRecordingSpecified
        {
            get
            {
                return this.earliestRecordingFieldSpecified;
            }
            set
            {
                this.earliestRecordingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public System.DateTime LatestRecording
        {
            get
            {
                return this.latestRecordingField;
            }
            set
            {
                this.latestRecordingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatestRecordingSpecified
        {
            get
            {
                return this.latestRecordingFieldSpecified;
            }
            set
            {
                this.latestRecordingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Track", Order = 5)]
        public TrackInformation[] Track
        {
            get
            {
                return this.trackField;
            }
            set
            {
                this.trackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public RecordingStatus RecordingStatus
        {
            get
            {
                return this.recordingStatusField;
            }
            set
            {
                this.recordingStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 7)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/schema")]
    public enum RecordingStatus
    {

        /// <remarks/>
        Initiated,

        /// <remarks/>
        Recording,

        /// <remarks/>
        Stopped,

        /// <remarks/>
        Removing,

        /// <remarks/>
        Removed,

        /// <remarks/>
        Unknown,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "SetMarker", WrapperNamespace = "urn:ias:cvss:mm:1.0", IsWrapped = true)]
    public partial class SetMarkerRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mm:1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("MediaSourceToken", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("RecordingToken", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mm:1.0", Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mm:1.0", Order = 2)]
        public MarkerInformation Marker;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mm:1.0", Order = 3)]
        public System.DateTime ExpirationTime;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;

        public SetMarkerRequest()
        {
        }

        public SetMarkerRequest(string Item, ItemChoiceType ItemElementName, MarkerInformation Marker, System.DateTime ExpirationTime, System.Xml.XmlElement[] Any)
        {
            this.Item = Item;
            this.ItemElementName = ItemElementName;
            this.Marker = Marker;
            this.ExpirationTime = ExpirationTime;
            this.Any = Any;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "SetMarkerResponse", WrapperNamespace = "urn:ias:cvss:mm:1.0", IsWrapped = true)]
    public partial class SetMarkerResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mm:1.0", Order = 0)]
        public string MarkerToken;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mm:1.0", Order = 1)]
        public System.DateTime ExpirationTime;

        public SetMarkerResponse()
        {
        }

        public SetMarkerResponse(string MarkerToken, System.DateTime ExpirationTime)
        {
            this.MarkerToken = MarkerToken;
            this.ExpirationTime = ExpirationTime;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetMarker", WrapperNamespace = "urn:ias:cvss:mm:1.0", IsWrapped = true)]
    public partial class GetMarkerRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mm:1.0", Order = 0)]
        public string MarkerToken;

        public GetMarkerRequest()
        {
        }

        public GetMarkerRequest(string MarkerToken)
        {
            this.MarkerToken = MarkerToken;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetMarkerResponse", WrapperNamespace = "urn:ias:cvss:mm:1.0", IsWrapped = true)]
    public partial class GetMarkerResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mm:1.0", Order = 0)]
        public MarkerInformation Marker;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mm:1.0", Order = 1)]
        public System.DateTime ExpirationTime;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mm:1.0", Order = 2)]
        public bool RecordingsReady;

        public GetMarkerResponse()
        {
        }

        public GetMarkerResponse(MarkerInformation Marker, System.DateTime ExpirationTime, bool RecordingsReady)
        {
            this.Marker = Marker;
            this.ExpirationTime = ExpirationTime;
            this.RecordingsReady = RecordingsReady;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetMarkedRecordings", WrapperNamespace = "urn:ias:cvss:mm:1.0", IsWrapped = true)]
    public partial class GetMarkedRecordingsRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mm:1.0", Order = 0)]
        public string MarkerToken;

        public GetMarkedRecordingsRequest()
        {
        }

        public GetMarkedRecordingsRequest(string MarkerToken)
        {
            this.MarkerToken = MarkerToken;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetMarkedRecordingsResponse", WrapperNamespace = "urn:ias:cvss:mm:1.0", IsWrapped = true)]
    public partial class GetMarkedRecordingsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mm:1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Recording")]
        public RecordingInformation[] Recording;

        public GetMarkedRecordingsResponse()
        {
        }

        public GetMarkedRecordingsResponse(RecordingInformation[] Recording)
        {
            this.Recording = Recording;
        }
    }


}
