//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaRestrictions
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "urn:ias:cvss:mrm:1.0", ConfigurationName = "MediaRestrictionsManager")]
    public interface IMediaRestrictionsManager
    {

        [System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:mrm:1.0/SetRestriction")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "RestrictionToken")]
        string SetRestriction(RestrictionType Restriction);

        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:mrm:1.0/GetRestrictions")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GetRestrictionsResponse GetRestrictions(GetRestrictionsRequest request);

        // CODEGEN: Параметр "RestrictionToken" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:mrm:1.0/ClearRestrictions")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ClearRestrictionsResponse ClearRestrictions(ClearRestrictionsRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:mrm:1.0")]
    public partial class RestrictionType
    {

        private string[] mediaSourceTokenField;

        private System.DateTime beginTimeField;

        private System.DateTime endTimeField;

        private string subjectField;

        private System.Xml.XmlElement[] anyField;

        private string tokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MediaSourceToken", Order = 0)]
        public string[] MediaSourceToken
        {
            get
            {
                return this.mediaSourceTokenField;
            }
            set
            {
                this.mediaSourceTokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.DateTime BeginTime
        {
            get
            {
                return this.beginTimeField;
            }
            set
            {
                this.beginTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public System.DateTime EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 4)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetRestrictions", WrapperNamespace = "urn:ias:cvss:mrm:1.0", IsWrapped = true)]
    public partial class GetRestrictionsRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mrm:1.0", Order = 0)]
        public int Limit;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mrm:1.0", Order = 1)]
        public string StartReference;

        public GetRestrictionsRequest()
        {
        }

        public GetRestrictionsRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetRestrictionsResponse", WrapperNamespace = "urn:ias:cvss:mrm:1.0", IsWrapped = true)]
    public partial class GetRestrictionsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mrm:1.0", Order = 0)]
        public string NextStartReference;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mrm:1.0", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("Restriction")]
        public RestrictionType[] Restriction;

        public GetRestrictionsResponse()
        {
        }

        public GetRestrictionsResponse(string NextStartReference, RestrictionType[] Restriction)
        {
            this.NextStartReference = NextStartReference;
            this.Restriction = Restriction;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ClearRestrictions", WrapperNamespace = "urn:ias:cvss:mrm:1.0", IsWrapped = true)]
    public partial class ClearRestrictionsRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:mrm:1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("RestrictionToken")]
        public string[] RestrictionToken;

        public ClearRestrictionsRequest()
        {
        }

        public ClearRestrictionsRequest(string[] RestrictionToken)
        {
            this.RestrictionToken = RestrictionToken;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ClearRestrictionsResponse", WrapperNamespace = "urn:ias:cvss:mrm:1.0", IsWrapped = true)]
    public partial class ClearRestrictionsResponse
    {

        public ClearRestrictionsResponse()
        {
        }
    }

}
