//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TaskManager
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "urn:ias:cvss:tm:1.0", ConfigurationName = "TaskManager")]
    public interface ITaskManager
    {

        [System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:tm:1.0/CreateTask")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "TaskToken")]
        string CreateTask(System.Xml.XmlElement Task, System.DateTime TimeBegin, System.DateTime TimeEnd, FeedbackType Feedback);

        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:tm:1.0/GetTaskStatus")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GetTaskStatusResponse GetTaskStatus(GetTaskStatusRequest request);

        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (urn:ias:cvss:tm:1.0).
        [System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:tm:1.0/GetTaskResults")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "Any")]
        GetTaskResultsResponse GetTaskResults(GetTaskResultsRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:tm:1.0/DeleteTask")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DeleteTask(string TaskToken);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:tm:1.0")]
    public partial class FeedbackType
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:tm:1.0")]
    public enum TaskStatus
    {

        /// <remarks/>
        NotActive,

        /// <remarks/>
        InProgress,

        /// <remarks/>
        Failed,

        /// <remarks/>
        Expired,

        /// <remarks/>
        Done,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetTaskStatus", WrapperNamespace = "urn:ias:cvss:tm:1.0", IsWrapped = true)]
    public partial class GetTaskStatusRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:tm:1.0", Order = 0)]
        public string TaskToken;

        public GetTaskStatusRequest()
        {
        }

        public GetTaskStatusRequest(string TaskToken)
        {
            this.TaskToken = TaskToken;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetTaskStatusResponse", WrapperNamespace = "urn:ias:cvss:tm:1.0", IsWrapped = true)]
    public partial class GetTaskStatusResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:tm:1.0", Order = 0)]
        public TaskStatus Status;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:tm:1.0", Order = 1)]
        public string Message;

        public GetTaskStatusResponse()
        {
        }

        public GetTaskStatusResponse(TaskStatus Status, string Message)
        {
            this.Status = Status;
            this.Message = Message;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetTaskResults", WrapperNamespace = "urn:ias:cvss:tm:1.0", IsWrapped = true)]
    public partial class GetTaskResultsRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:tm:1.0", Order = 0)]
        public string TaskToken;

        public GetTaskResultsRequest()
        {
        }

        public GetTaskResultsRequest(string TaskToken)
        {
            this.TaskToken = TaskToken;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetTaskResultsResponse", WrapperNamespace = "urn:ias:cvss:tm:1.0", IsWrapped = true)]
    public partial class GetTaskResultsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any;

        public GetTaskResultsResponse()
        {
        }

        public GetTaskResultsResponse(System.Xml.XmlElement Any)
        {
            this.Any = Any;
        }
    }
    public class Task
    {
        public ScheduledRecordingTask scheduledRecordingTask;
    }
    class ScheduledRecordingTask
    {
        public string mediaSourceToken { get; set; }
    }
}
