// This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++ and C#: http://www.viva64.com

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ServiceModel;

namespace MediaSourcesProvider
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "urn:ias:cvss:msp:1.0",
        ConfigurationName = "MediaSourcesProvider"),
    XmlSerializerFormat,
    OnvifProxy.SecurityContractBehavior]
    public interface IMediaSourcesProvider
    {
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения (http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd) не соответствует значению по умолчанию (urn:ias:cvss:msp:1.0).
        //[System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:msp:1.0/GetMediaSources")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EndpointReferenceType))]
        [System.ServiceModel.OperationContractAttribute(ReplyAction = "*", Action="*"),
       OnvifProxy.SecurityOperationBehavoir("GetMediaSources", "urn:ias:cvss:msp:1.0", 3)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "NextStartReference")]
        GetMediaSourcesResponse GetMediaSources(GetMediaSourcesRequest request);

        //GetMediaSourcesResponse GetMediaSources();

        // CODEGEN: Параметр "KeepAliveTime" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        //[System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:msp:1.0/FindMediaSources")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EndpointReferenceType))]
        [System.ServiceModel.OperationContractAttribute(ReplyAction = "*"),
      OnvifProxy.SecurityOperationBehavoir("FindMediaSources", "urn:ias:cvss:msp:1.0", 3)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "SearchToken")]
        FindMediaSourcesResponse FindMediaSources(FindMediaSourcesRequest request);

        // CODEGEN: Параметр "WaitTime" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        //[System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:msp:1.0/GetSearchResults")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EndpointReferenceType))]
        [System.ServiceModel.OperationContractAttribute(ReplyAction = "*"),
      OnvifProxy.SecurityOperationBehavoir("GetSearchResults", "urn:ias:cvss:msp:1.0", 3)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "SearchState")]
        GetSearchResultsResponse GetSearchResults(GetSearchResultsRequest request);

        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения (http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd) не соответствует значению по умолчанию (urn:ias:cvss:msp:1.0).
        //[System.ServiceModel.OperationContractAttribute(Action = "urn:ias:cvss:msp:1.0/GetUpdates")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EndpointReferenceType))]
        [System.ServiceModel.OperationContractAttribute(ReplyAction = "*"),
     OnvifProxy.SecurityOperationBehavoir("GetUpdates", "urn:ias:cvss:msp:1.0", 3)]
        GetUpdatesResponse GetUpdates(GetUpdatesRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class SecurityHeaderType
    {

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:msp:1.0")]
    public partial class UpdateType
    {

        private string mediaSourceTokenField;

        private MediaSourceType mediaSourceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string MediaSourceToken
        {
            get
            {
                return this.mediaSourceTokenField;
            }
            set
            {
                this.mediaSourceTokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public MediaSourceType MediaSource
        {
            get
            {
                return this.mediaSourceField;
            }
            set
            {
                this.mediaSourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:msp:1.0")]
    public partial class MediaSourceType
    {

        private ONVIFBindingType oNVIFBindingField;

        private NameType[] nameField;

        private DescriptionType[] descriptionField;

        private GeoCircle locationField;

        private GeoPolygon viewAreaField;

        private string tokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ONVIFBindingType ONVIFBinding
        {
            get
            {
                return this.oNVIFBindingField;
            }
            set
            {
                this.oNVIFBindingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Name", Order = 1)]
        public NameType[] Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description", Order = 2)]
        public DescriptionType[] Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public GeoCircle Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public GeoPolygon ViewArea
        {
            get
            {
                return this.viewAreaField;
            }
            set
            {
                this.viewAreaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:msp:1.0")]
    public partial class ONVIFBindingType
    {

        private EndpointType[] endpointField;

        private string mediaSourceTokenField;

        private string profileTokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Endpoint", Order = 0)]
        public EndpointType[] Endpoint
        {
            get
            {
                return this.endpointField;
            }
            set
            {
                this.endpointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string MediaSourceToken
        {
            get
            {
                return this.mediaSourceTokenField;
            }
            set
            {
                this.mediaSourceTokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ProfileToken
        {
            get
            {
                return this.profileTokenField;
            }
            set
            {
                this.profileTokenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:msp:1.0")]
    public partial class EndpointType : EndpointReferenceType
    {

        private string[] purposeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string[] purpose
        {
            get
            {
                return this.purposeField;
            }
            set
            {
                this.purposeField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EndpointType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2005/08/addressing")]
    public partial class EndpointReferenceType
    {

        private AttributedURIType addressField;

        private ReferenceParametersType referenceParametersField;

        private MetadataType metadataField;

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public AttributedURIType Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ReferenceParametersType ReferenceParameters
        {
            get
            {
                return this.referenceParametersField;
            }
            set
            {
                this.referenceParametersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public MetadataType Metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 3)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2005/08/addressing")]
    public partial class AttributedURIType
    {

        private System.Xml.XmlAttribute[] anyAttrField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "anyURI")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2005/08/addressing")]
    public partial class ReferenceParametersType
    {

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2005/08/addressing")]
    public partial class MetadataType
    {

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:msp:1.0")]
    public partial class NameType
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:msp:1.0")]
    public partial class DescriptionType
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:1.0")]
    public partial class GeoCircle
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:1.0")]
    public partial class GeoPolygon
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:msp:1.0")]
    public partial class SearchScopeType
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetMediaSources", WrapperNamespace = "urn:ias:cvss:msp:1.0", IsWrapped = true)]
    public partial class GetMediaSourcesRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 0)]
        public int Limit;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 1)]
        public string StartReference;

        public GetMediaSourcesRequest()
        {
        }

        public GetMediaSourcesRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetMediaSourcesResponse", WrapperNamespace = "urn:ias:cvss:msp:1.0", IsWrapped = true)]
    public partial class GetMediaSourcesResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 0)]
        public string NextStartReference;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 1)]
        public string UpdateToken;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public SecurityHeaderType Security;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute("MediaSource")]
        public MediaSourceType[] MediaSource;

        public GetMediaSourcesResponse()
        {
        }

        public GetMediaSourcesResponse(string NextStartReference, string UpdateToken, SecurityHeaderType Security, MediaSourceType[] MediaSource)
        {
            this.NextStartReference = NextStartReference;
            this.UpdateToken = UpdateToken;
            this.Security = Security;
            this.MediaSource = MediaSource;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FindMediaSources", WrapperNamespace = "urn:ias:cvss:msp:1.0", IsWrapped = true)]
    public partial class FindMediaSourcesRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 0)]
        public SearchScopeType Scope;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 1)]
        public int MaxMatches;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string KeepAliveTime;

        public FindMediaSourcesRequest()
        {
        }

        public FindMediaSourcesRequest(SearchScopeType Scope, int MaxMatches, string KeepAliveTime)
        {
            this.Scope = Scope;
            this.MaxMatches = MaxMatches;
            this.KeepAliveTime = KeepAliveTime;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FindMediaSourcesResponse", WrapperNamespace = "urn:ias:cvss:msp:1.0", IsWrapped = true)]
    public partial class FindMediaSourcesResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 0)]
        public string SearchToken;

        public FindMediaSourcesResponse()
        {
        }

        public FindMediaSourcesResponse(string SearchToken)
        {
            this.SearchToken = SearchToken;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ias:cvss:msp:1.0")]
    public enum SearchStateEnum
    {

        /// <remarks/>
        Searching,

        /// <remarks/>
        Completed,

        /// <remarks/>
        Unknown,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetSearchResults", WrapperNamespace = "urn:ias:cvss:msp:1.0", IsWrapped = true)]
    public partial class GetSearchResultsRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 0)]
        public string SearchToken;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 1)]
        public int MinResults;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 2)]
        public int MaxResults;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string WaitTime;

        public GetSearchResultsRequest()
        {
        }

        public GetSearchResultsRequest(string SearchToken, int MinResults, int MaxResults, string WaitTime)
        {
            this.SearchToken = SearchToken;
            this.MinResults = MinResults;
            this.MaxResults = MaxResults;
            this.WaitTime = WaitTime;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetSearchResultsResponse", WrapperNamespace = "urn:ias:cvss:msp:1.0", IsWrapped = true)]
    public partial class GetSearchResultsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 0)]
        public SearchStateEnum SearchState;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public SecurityHeaderType Security;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute("MediaSource")]
        public MediaSourceType[] MediaSource;

        public GetSearchResultsResponse()
        {
        }

        public GetSearchResultsResponse(SearchStateEnum SearchState, SecurityHeaderType Security, MediaSourceType[] MediaSource)
        {
            this.SearchState = SearchState;
            this.Security = Security;
            this.MediaSource = MediaSource;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetUpdates", WrapperNamespace = "urn:ias:cvss:msp:1.0", IsWrapped = true)]
    public partial class GetUpdatesRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 0)]
        public string UpdateToken;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 1)]
        public int Limit;

        public GetUpdatesRequest()
        {
        }

        public GetUpdatesRequest(string UpdateToken, int Limit)
        {
            this.UpdateToken = UpdateToken;
            this.Limit = Limit;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetUpdatesResponse", WrapperNamespace = "urn:ias:cvss:msp:1.0", IsWrapped = true)]
    public partial class GetUpdatesResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 0)]
        public string UpdateToken;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 1)]
        public bool HasMoreUpdates;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public SecurityHeaderType Security;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:ias:cvss:msp:1.0", Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute("Update")]
        public UpdateType[] Update;

        public GetUpdatesResponse()
        {
        }

        public GetUpdatesResponse(string UpdateToken, bool HasMoreUpdates, SecurityHeaderType Security, UpdateType[] Update)
        {
            this.UpdateToken = UpdateToken;
            this.HasMoreUpdates = HasMoreUpdates;
            this.Security = Security;
            this.Update = Update;
        }
    }


    //public class MediaSourcesProvider: IMediaSourcesProvider
    //public partial class Service1 : Device.IDevice,
    //    Media.IMedia,
    //    Event.INotificationProducer,
    //    Event.IEventPortType,
    //    Event.IPullPoint,
    //    Event.ICreatePullPoint,
    //    Event.SubscriptionManager,
    //    Event.IPausableSubscriptionManager,
    //    Event.INotificationConsumer,
    //    Event.PullPointSubscription,
    //    MediaSourcesProvider.IMediaSourcesProvider//added
    //{
    //    public GetMediaSourcesResponse GetMediaSources(GetMediaSourcesRequest request)
    //    {
    //        return new GetMediaSourcesResponse();
    //    }

    //    public FindMediaSourcesResponse FindMediaSources(FindMediaSourcesRequest request)
    //    {
    //        return new FindMediaSourcesResponse();
    //    }


    //    public GetSearchResultsResponse GetSearchResults(GetSearchResultsRequest request)
    //    {
    //        return new GetSearchResultsResponse();
    //    }

    //    public GetUpdatesResponse GetUpdates(GetUpdatesRequest request)
    //    {
    //        return new GetUpdatesResponse();
    //    }
    //}
}
